fix(cat-voices): update key derivation path
input-output-hk/catalyst-voices pull request #1301
Opened 2024-11-29 10:04 UTC by dtscalac

# Description

Updates key derivation path based on new specification: https://github.com/input-output-hk/catalyst-voices/pull/1300

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

2024-11-29 12:45 UTC, dtscalac commented on catalyst_voices/packages/internal/catalyst_voices_models/lib/src/user/account_role.dart
>    final int roleNumber;
done

2024-11-29 12:45 UTC, dtscalac commented on catalyst_voices/packages/internal/catalyst_voices_services/lib/src/crypto/key_derivation.dart
> +    return "m/508'/139'/0'/${role.roleNumber}/0";
done

2024-11-29 12:53 UTC, damian-molinski approved these changes
LGTM

2024-11-29 13:32 UTC, stevenj requested changes
Changes are not required, just a suggestion.
Otherwise LGTM

2024-11-29 13:32 UTC, stevenj commented on catalyst_voices/packages/internal/catalyst_voices_services/lib/src/crypto/key_derivation.dart
> +
Just for alignment with the spec,  I suggest adding this.
```suggestion
static const int _account = 0; // Future Use
```

2024-11-29 13:32 UTC, stevenj commented on catalyst_voices/packages/internal/catalyst_voices_services/lib/src/crypto/key_derivation.dart
> +    return "m/$_purpose'/$_type'/0'/${role.number}/0";
```suggestion
    return "m/$_purpose'/$_type'/$_account'/${role.number}/0";
```

2024-12-02 08:17 UTC, damian-molinski approved these changes

2024-12-02 09:35 UTC, stevenj approved these changes
LGTM

2024-12-02 09:36 UTC, merged