test(cat-gateway): Add integration test to IndexDB
input-output-hk/catalyst-voices pull request #1431
Opened 2024-12-23 14:20 UTC by apskhem

# Description

Added integration test to test validity of Scylla (IndexDB) queries.

## Related Issue(s)

Closes #1318 

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

2024-12-24 08:52 UTC, kukkok3 reviewed
Can you pls move the `test-scylla` and `test-postgres` target in the Earthfile in catalyst-gateway/tests so we dont clogh up the catalyst-gateway earthfile with other targets?

2025-01-02 02:13 UTC, bkioshn commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +async fn test_get_chain_root() -> Result<(), String> {
Should it be `test_get_chain_root_by_stake_addr` ?

2025-01-02 02:13 UTC, bkioshn commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +async fn test_get_role0_key_chain_root() -> Result<(), String> {
Should it be `test_get_chain_root_by_role0`?

2025-01-02 03:24 UTC, apskhem commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +const FAILED_READING_ROW_MSG: &str = "Failed executing query";
Thanks for spotting.

2025-01-02 03:28 UTC, apskhem commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +async fn test_get_chain_root() -> Result<(), String> {
All the tests here are named after its `cql` file. So there's no need to change on this, unless we have another test on the same `cql` file.

2025-01-03 08:43 UTC, Mr-Leshiy commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +async fn test_get_assets_by_stake_addr() -> Result<(), String> {
I would prefer not to return an error for test functions.

When some function execution inside the test failed, it will be hardly to determine where it was failed, so I assume that is why you are making your own error messages like `FAILED_EXECUTING_QUERY_MSG`, `FAILED_READING_ROW_MSG`.

I would rather just make a test function without any return type and use `unwrap` or `expect` (if you want provide some additional text message)

2025-01-03 08:59 UTC, apskhem commented on catalyst-gateway/bin/src/db/index/tests/scylla_queries.rs
> +async fn test_get_assets_by_stake_addr() -> Result<(), String> {
I see. That would also be much cleaner, then I'll use `unwrap` instead for simplication. I had overlooked that we can use `unwrap` and `expect` Inside tests.

2025-01-03 10:21 UTC, stevenj requested changes
Make slow tests be reported at 30 seconds, and timeout after 1 minute.

2025-01-03 11:22 UTC, Mr-Leshiy submitted a review, later dismissed
LGTM

2025-01-03 12:44 UTC, stevenj approved these changes
LGTM

2025-01-03 12:54 UTC, merged