feat: add openapi linter
input-output-hk/catalyst-voices pull request #208
Opened 2024-01-13 07:09 UTC by bkioshn

# Description

Create a openAPI linter target.

## Related Issue(s)

List the issue numbers related to this pull request.

Closes #143 

## Description of Changes

- Create an openAPI linter target named `check-lint-openapi`
- Add spectral rule set including
    - [OWASP TOP 10](https://apistylebook.stoplight.io/docs/owasp-top-10)
    - [Spectral Documentation](https://github.com/stoplightio/spectral-documentation)
    - [OpenAPI](https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#openapi-rules)
- Create `BUILD_SPECTRAL` function 

## Breaking Changes

## Screenshots

## Related Pull Requests

## Please confirm the following checks

* [x] My code follows the style guidelines of this project
* [x] I have performed a self-review of my code
* [x] I have commented my code, particularly in hard-to-understand areas
* [x] I have made corresponding changes to the documentation
* [x] My changes generate no new warnings
* [x] I have added tests that prove my fix is effective or that my feature works
* [x] New and existing unit tests pass locally with my changes
* [x] Any dependent changes have been merged and published in downstream module

2024-02-06 09:38 UTC, stevenj requested changes

2024-02-06 09:38 UTC, stevenj commented on catalyst-gateway/.spectral.yml
> +    owasp:api1:2019-no-numeric-ids: off
Make this global to all.

2024-02-06 09:38 UTC, stevenj commented on catalyst-gateway/.spectral.yml
> +    owasp:api7:2019-security-hosts-https-oas3: off
remove this when the server changes are completed

2024-02-07 14:38 UTC, stevenj approved these changes
LGTM

2024-02-07 15:21 UTC, minikin approved these changes

2024-02-07 15:21 UTC, merged