feat(ci): add earthfile for voices fronted
input-output-hk/catalyst-voices pull request #263
Opened 2024-02-23 12:12 UTC by minikin

- Prepare Catalyst Voices Web for deployment

2024-02-23 15:36 UTC, jmgilman requested changes

2024-02-23 15:36 UTC, jmgilman commented on catalyst_voices/Earthfile
> +VERSION --try --global-cache 0.8
Looks like CI is failing, try setting this to `0.7`

2024-02-23 16:07 UTC, minikin commented on catalyst_voices/Earthfile
> +flutter:
FYI @jmgilman we will extract this into catalyst-ci in another task.

2024-02-23 16:08 UTC, minikin commented
FYI @jmgilman we will extract `flutter` install and config into catalyst-ci in another task.

2024-02-23 16:09 UTC, stevenj requested changes
Looks good, except for the one suggestion.

2024-02-23 16:09 UTC, stevenj commented on catalyst_voices/Earthfile
> +publish:
```suggestion
package:
```
this should be `package:`  to align with CI.  `publish` actually publishes a prebuilt package, whereas this is just building the package ready to publish.

2024-02-26 05:19 UTC, stevenj approved these changes

2024-02-26 06:40 UTC, merged