docs: Add CatalystDataGatewayRepository docs
input-output-hk/catalyst-voices pull request #388
Opened 2024-04-08 09:15 UTC by coire1

# Description

This PR adds usage examples for the `CatalystDataGatewayRepository` and fixes the failing tests.

## Related Issue(s)

List the issue numbers related to this pull request.

Closes #350

2024-04-08 10:54 UTC, stevenj requested changes
Rather than as individual readme files, I think we should have this kind of documentation in the docs themselves.  Can they be moved to the docs in a section for our Dart API's?

2024-04-09 12:20 UTC, coire1 commented
@stevenj we agreed with @minikin to movethe content of the README as code comments, leaving the README as it was before. 
Mock instructions are not necessary anymore.

2024-04-09 12:29 UTC, dtscalac commented on catalyst_voices/packages/catalyst_voices_repositories/test/src/catalyst_data_gateway_repository/catalyst_data_gateway_repository_test.dart
> +  Future<chopper.Response<dynamic>> apiHealthStartedGet() async {
How about using expressions here?

```
@override
Future<chopper.Response<dynamic>> apiHealthStartedGet() async => response;
```

For one-liners, especially if there are plenty of them helps to reduce the vertical space it takes

2024-04-09 12:31 UTC, dtscalac commented on catalyst_voices/packages/catalyst_voices_repositories/test/src/catalyst_data_gateway_repository/catalyst_data_gateway_repository_test.dart
> +        chopper.Response(http.Response('', 200), null),
Would `HttpStatus.ok` status work here? It gives a meaningful name to a status code. Wdyt? There will be more places to replace this if you agree:)

2024-04-10 02:07 UTC, stevenj commented
As this is not a M2 deliverable, can we retarget the PR to the `feat/m3` branch?
I am trying to reduce churn on `main` leading up to tagging it as the Milestone 2 release.

2024-04-10 10:59 UTC, merged