feat: C509 `Name` type
input-output-hk/catalyst-voices pull request #604
Opened 2024-07-10 11:43 UTC by bkioshn

# Description

 Implement encode and decode for C509 `Name` type

## Related Issue(s)

Closes #589 

## Description of Changes

Provide a clear and concise description of what the pull request changes.

## Breaking Changes

Describe any breaking changes and the impact.

## Screenshots

If applicable, add screenshots to help explain your changes.

## Related Pull Requests

If applicable, list any related pull requests.

> e.g., #1, #1

## Please confirm the following checks

* [ ] My code follows the style guidelines of this project
* [ ] I have performed a self-review of my code
* [ ] I have commented my code, particularly in hard-to-understand areas
* [ ] I have made corresponding changes to the documentation
* [ ] My changes generate no new warnings
* [ ] I have added tests that prove my fix is effective or that my feature works
* [ ] New and existing unit tests pass locally with my changes
* [ ] Any dependent changes have been merged and published in downstream module

2024-07-10 13:22 UTC, stevenj requested changes
Looks good except for my single request for change.

2024-07-10 13:22 UTC, stevenj commented on catalyst-gateway-crates/c509-certificate/src/c509_attributes/data.rs
> +pub(crate) static ATTRIBUTES_LOOKUP: &Lazy<AttributeData> = &ATTRIBUTES_TABLES;
Don't have `pub(crate)` on static structures.
Make it private to the file and accessor functions to query/update it.

2024-07-10 13:58 UTC, stevenj commented on catalyst-gateway-crates/c509-certificate/src/c509_attributes/data.rs
> +pub(crate) static ATTRIBUTES_LOOKUP: &Lazy<AttributeData> = &ATTRIBUTES_TABLES;
I am ok with this, now, given how it is used.

2024-07-10 13:59 UTC, stevenj approved these changes
LGTM

2024-07-11 14:41 UTC, apskhem approved these changes

2024-07-12 00:21 UTC, merged